### ISSUE TITLE
install example scripts

### ISSUE THREAD

**Issue by mithrandir42** [gemian/gemian-leds#1]
The example scripts do not get installed when installing gemian-leds. Please install the scripts with the debian package. Then the average user can get an idea on how to use gemian-leds without cloning the repo. Maybe somewhere in /usr/share/doc?

Btw. Great work, thanks.

**Comment by adamboardman** [comment]
Should be installable with gemian-leds-scripts?

(The idea is to have a UI to let you edit patterns and associate with contacts for calls etc, but that'd not done just yet)

**Comment by mithrandir42** [comment]
Mostly right ;) Just built from source and the scripts .deb gets built (dpkg-buildpackage -us -uc). 

Somehow the package is not part of the Debian repo. Maybe you could just add the upload to your build process or what is the process for getting packages into the repo? I am just curious how it works.

A GUI for sure is nice, but for some non standard notification tasks scripts are more flexible and anyways currently the only way to go.

**Comment by adamboardman** [comment]
Good catch, scripts is arch independent so needed to change the jenkins server to build amd64 as well as arm64. Server setup as per wiki, see https://github.com/gemian/gemini-keyboard-apps/wiki/BuildServer
